<?php
/**
 * @file
 * Code for the Communication feature.
 */

include_once 'chancellor_communication.features.inc';

function chancellor_communication_node_view($node, $view_mode) {
  if (($node->type == 'communication') && ($view_mode == 'full') && (!empty($node->field_communication_link[LANGUAGE_NONE][0]['url']))) {
    $redirect = $node->field_communication_link[LANGUAGE_NONE][0]['url'];
    if (user_access("edit any communication content")) {
      drupal_set_message(t('A user without editing permissions would have been redirected to !redirect',
          array('!redirect' => l($redirect, $redirect))),
        'notice');
    }
    else {
      drupal_goto($redirect);
    }
  }

}

/*
 * Implements hook_secure_permissions
 *
 * Adding permissions for video reveal bean
 */
function chancellor_communication_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(),
    'authenticated user' => array(),
    'administrator' => array(
      'create communication content',
      'delete any communication content',
      'delete own communication content',
      'edit any communication content',
      'edit own communication content',
    ),
    'content_editor' => array(
      'create communication content',
      'delete any communication content',
      'delete own communication content',
      'edit any communication content',
      'edit own communication content',
    ),
    'developer' => array(
      'create communication content',
      'delete any communication content',
      'delete own communication content',
      'edit any communication content',
      'edit own communication content',
    ),
    'site_owner' => array(
      'create communication content',
      'delete any communication content',
      'delete own communication content',
      'edit any communication content',
      'edit own communication content',
    ),
  );
  return $permissions[$role];
}
