<?php
/**
 * @file
 * Code for the Communication feature.
 */

include_once 'chancellor_communication.features.inc';

function chancellor_communication_node_view($node, $view_mode) {
  if (($node->type == 'communication') && ($view_mode == 'full') && (!empty($node->field_communication_link[LANGUAGE_NONE][0]['url']))) {
    $redirect = $node->field_communication_link[LANGUAGE_NONE][0]['url'];
    if (user_access("edit any communication content")) {
      drupal_set_message(t('A user without editing permissions would have been redirected to !redirect',
          array('!redirect' => l($redirect, $redirect))),
        'notice');
    }
    else {
      drupal_goto($redirect);
    }
  }

}
