<?php
/**
 * @file
 * Code for the In the News feature.
 */

include_once 'chancellor_in_the_news.features.inc';

/*
 * Implements hook_secure_permissions
 *
 * Adding permissions for in_the_news nodes
 */
function chancellor_in_the_news_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(

    ),
    'authenticated user' => array(

    ),
    'administrator' => array(
      'create in_the_news content',
      'delete any in_the_news content',
      'delete own in_the_news content',
      'edit any in_the_news content',
      'edit own in_the_news content',
    ),
    'content_editor' => array(
      'create in_the_news content',
      'delete any in_the_news content',
      'delete own in_the_news content',
      'edit any in_the_news content',
      'edit own in_the_news content',
    ),
    'developer' => array(
      'create in_the_news content',
      'delete any in_the_news content',
      'delete own in_the_news content',
      'edit any in_the_news content',
      'edit own in_the_news content',
    ),
    'site_owner' => array(
      'create in_the_news content',
      'delete any in_the_news content',
      'delete own in_the_news content',
      'edit any in_the_news content',
      'edit own in_the_news content',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
